// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Detects the BPM and key of a song given its title and artist.
 *
 * - detectBpmAndKey - A function that detects the BPM and key of a song.
 * - DetectBpmAndKeyInput - The input type for the detectBpmAndKey function.
 * - DetectBpmAndKeyOutput - The return type for the detectBpmAndKey function.
 */

import {ai} from '@/ai/genkit';
import { getSongDetails, SongDetailsSchema } from '@/services/music-service';
import {z} from 'genkit';

const DetectBpmAndKeyInputSchema = z.object({
  title: z.string().describe('The title of the song.'),
  artist: z.string().describe('The artist of the song.'),
});
export type DetectBpmAndKeyInput = z.infer<typeof DetectBpmAndKeyInputSchema>;

const DetectBpmAndKeyOutputSchema = z.object({
  bpm: z.number().describe('The BPM (beats per minute) of the song.'),
  key: z.string().describe('The musical key of the song (e.g., C major, A minor).'),
  duration: z.string().describe('The duration of the song in MM:SS format.'),
});
export type DetectBpmAndKeyOutput = z.infer<typeof DetectBpmAndKeyOutputSchema>;

export async function detectBpmAndKey(input: DetectBpmAndKeyInput): Promise<DetectBpmAndKeyOutput> {
  return detectBpmAndKeyFlow(input);
}

const getSongDetailsTool = ai.defineTool(
  {
    name: 'getSongDetails',
    description: 'Get the details of a song, including BPM, key, and duration.',
    inputSchema: DetectBpmAndKeyInputSchema,
    outputSchema: SongDetailsSchema,
  },
  async (input) => {
    return getSongDetails(input);
  }
);


const prompt = ai.definePrompt({
  name: 'detectBpmAndKeyPrompt',
  input: {schema: DetectBpmAndKeyInputSchema},
  output: {schema: DetectBpmAndKeyOutputSchema},
  prompt: `You are an AI music expert. Use the provided tool to get the details for the song.

  Song Title: {{{title}}}
  Artist: {{{artist}}}

  Respond with the exact BPM, key, and duration provided by the tool. Do not guess or use your own knowledge.`,
  tools: [getSongDetailsTool],
});

const detectBpmAndKeyFlow = ai.defineFlow(
  {
    name: 'detectBpmAndKeyFlow',
    inputSchema: DetectBpmAndKeyInputSchema,
    outputSchema: DetectBpmAndKeyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
