// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Detects the BPM and key of a song given its title and artist.
 *
 * - detectBpmAndKey - A function that detects the BPM and key of a song.
 * - DetectBpmAndKeyInput - The input type for the detectBpmAndKey function.
 * - DetectBpmAndKeyOutput - The return type for the detectBpmAndKey function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectBpmAndKeyInputSchema = z.object({
  title: z.string().describe('The title of the song.'),
  artist: z.string().describe('The artist of the song.'),
});
export type DetectBpmAndKeyInput = z.infer<typeof DetectBpmAndKeyInputSchema>;

const DetectBpmAndKeyOutputSchema = z.object({
  bpm: z.number().describe('The BPM (beats per minute) of the song.'),
  key: z.string().describe('The musical key of the song (e.g., C major, A minor).'),
  duration: z.string().describe('The duration of the song in MM:SS format.'),
});
export type DetectBpmAndKeyOutput = z.infer<typeof DetectBpmAndKeyOutputSchema>;

export async function detectBpmAndKey(input: DetectBpmAndKeyInput): Promise<DetectBpmAndKeyOutput> {
  return detectBpmAndKeyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'detectBpmAndKeyPrompt',
  input: {schema: DetectBpmAndKeyInputSchema},
  output: {schema: DetectBpmAndKeyOutputSchema},
  prompt: `You are an AI music expert. Given a song title and artist, you will determine the BPM, key, and duration of the song.

  Song Title: {{{title}}}
  Artist: {{{artist}}}

  Respond with the BPM as a number, the key as a string (e.g. C major), and the duration as a string in MM:SS format.`,
});

const detectBpmAndKeyFlow = ai.defineFlow(
  {
    name: 'detectBpmAndKeyFlow',
    inputSchema: DetectBpmAndKeyInputSchema,
    outputSchema: DetectBpmAndKeyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
