// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Generates a description for a song.
 *
 * - generateSongDescription - A function that generates a song description.
 * - GenerateSongDescriptionInput - The input type for the generateSongDescription function.
 * - GenerateSongDescriptionOutput - The return type for the generateSongDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSongDescriptionInputSchema = z.object({
  title: z.string().describe('The title of the song.'),
  artist: z.string().describe('The artist of the song.'),
    bpm: z.number().describe('The BPM of the song.'),
    key: z.string().describe('The key of the song.'),
    duration: z.string().describe('The duration of the song.'),
});
export type GenerateSongDescriptionInput = z.infer<typeof GenerateSongDescriptionInputSchema>;

const GenerateSongDescriptionOutputSchema = z.object({
  description: z.string().describe('A detailed description of the song, including its musical characteristics.'),
});
export type GenerateSongDescriptionOutput = z.infer<typeof GenerateSongDescriptionOutputSchema>;

export async function generateSongDescription(input: GenerateSongDescriptionInput): Promise<GenerateSongDescriptionOutput> {
  return generateSongDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSongDescriptionPrompt',
  input: {schema: GenerateSongDescriptionInputSchema},
  output: {schema: GenerateSongDescriptionOutputSchema},
  prompt: `You are a music expert. Write a short, engaging paragraph describing the song "{{title}}" by {{artist}}.

Include the following details in your description:
- Tempo (BPM): {{bpm}}
- Key: {{key}}
- Duration: {{duration}}

Talk about its energy, danceability, and any other interesting musical characteristics. Mention potential uses like half-time or double-time if applicable.
`,
});

const generateSongDescriptionFlow = ai.defineFlow(
  {
    name: 'generateSongDescriptionFlow',
    inputSchema: GenerateSongDescriptionInputSchema,
    outputSchema: GenerateSongDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
