// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Provides a daily list of songs.
 *
 * - getDailySongs - A function that returns a list of 5 songs for the day.
 * - DailySong - The type for a song entry.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const DailySongSchema = z.object({
    artist: z.string(),
    title: z.string(),
});
export type DailySong = z.infer<typeof DailySongSchema>;

const DailySongsOutputSchema = z.array(DailySongSchema);

export async function getDailySongs(): Promise<DailySong[]> {
    return getDailySongsFlow();
}

const getDailySongsFlow = ai.defineFlow(
    {
        name: 'getDailySongsFlow',
        inputSchema: z.void(),
        outputSchema: DailySongsOutputSchema,
    },
    async () => {
        // This list will be the same for the whole day, based on the date.
        // A more advanced implementation could use a database or an external API.
        const songs = [
            { artist: 'Bleu Grave', title: 'Your Idol' },
            { artist: 'Helene Fischer', title: 'Herzbeben' },
            { artist: 'Engelbert Humperdinck', title: 'Quando Quando Quando' },
            { artist: 'Daft Punk', title: 'Around the World' },
            { artist: 'Fleetwood Mac', title: 'Dreams' },
        ];
        
        const dayOfYear = Math.floor((new Date().getTime() - new Date(new Date().getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
        const startIndex = dayOfYear % songs.length;
        
        const dailySongs = [];
        for (let i = 0; i < 5; i++) {
            dailySongs.push(songs[(startIndex + i) % songs.length]);
        }
        
        return dailySongs;
    }
);
