// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Provides a daily list of songs.
 *
 * - getTrendingSongs - A function that returns a list of 9 songs for the day.
 * - TrendingSong - The type for a song entry.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const TrendingSongSchema = z.object({
    artist: z.string(),
    title: z.string(),
});
export type TrendingSong = z.infer<typeof TrendingSongSchema>;

const TrendingSongsOutputSchema = z.array(TrendingSongSchema);

export async function getTrendingSongs(): Promise<TrendingSong[]> {
    return getTrendingSongsFlow();
}

const getTrendingSongsFlow = ai.defineFlow(
    {
        name: 'getTrendingSongsFlow',
        inputSchema: z.void(),
        outputSchema: TrendingSongsOutputSchema,
    },
    async () => {
        // This list will be the same for the whole day, based on the date.
        // A more advanced implementation could use a database or an external API.
        const songs = [
            { artist: 'Sabrina Carpenter', title: 'Espresso' },
            { artist: 'Post Malone', title: 'I Had Some Help' },
            { artist: 'Kendrick Lamar', title: 'Not Like Us' },
            { artist: 'Tommy Richman', title: 'Million Dollar Baby' },
            { artist: 'Shaboozey', title: 'A Bar Song (Tipsy)' },
            { artist: 'Billie Eilish', title: 'Birds of a Feather' },
            { artist: 'Hozier', title: 'Too Sweet' },
            { artist: 'Taylor Swift', title: 'Fortnight' },
            { artist: 'Benson Boone', title: 'Beautiful Things' },
        ];
        
        const dayOfYear = Math.floor((new Date().getTime() - new Date(new Date().getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
        const startIndex = dayOfYear % songs.length;
        
        const dailySongs = [];
        for (let i = 0; i < 9; i++) {
            dailySongs.push(songs[(startIndex + i) % songs.length]);
        }
        
        return dailySongs;
    }
);
