
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function PrivacyPolicyPage() {
    return (
        <main className="container mx-auto px-4 py-8">
            <Card className="max-w-3xl mx-auto">
                <CardHeader>
                    <CardTitle className="text-3xl">Privacy Policy</CardTitle>
                </CardHeader>
                <CardContent className="space-y-6 text-muted-foreground">
                    <p>Last updated: July 16, 2025</p>

                    <p>Welcome to TuneDetective. This Privacy Policy explains how we collect, use, and protect your information when you use our Service. By using our application, you agree to the collection and use of information in accordance with this policy.</p>

                    <div className="space-y-4">
                        <h2 className="text-2xl font-semibold text-foreground">1. Interpretation and Definitions</h2>
                        <h3 className="text-xl font-semibold text-foreground">Interpretation</h3>
                        <p>Words with initial capital letters are defined under the following conditions. These definitions apply whether they appear in singular or plural form.</p>

                        <h3 className="text-xl font-semibold text-foreground">Definitions</h3>
                        <p>For the purposes of this Privacy Policy:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li><strong>Company</strong> (referred to as "the Company", "We", "Us", or "Our") refers to TuneDetective.</li>
                            <li><strong>Service</strong> refers to the TuneDetective website and all related services accessible from the current domain.</li>
                            <li><strong>You</strong> refers to the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is using the Service.</li>
                            <li><strong>Device</strong> means any device that can access the Service, such as a computer, smartphone, or tablet.</li>
                            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by using the Service or from the Service's infrastructure (e.g., the duration of a page visit).</li>
                             <li><strong>Cookies</strong> are small files placed on your Device by a website, containing details of your browsing history.</li>
                        </ul>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-2xl font-semibold text-foreground">2. Collecting and Using Your Data</h2>
                         <h3 className="text-xl font-semibold text-foreground">Types of Data Collected</h3>
                        <p>While using our Service, we may collect certain types of information:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li><strong>Personal Data:</strong> We currently do not require you to create an account or provide personally identifiable information like your name or email. The only data that may be considered personal is your Usage Data as described below.</li>
                            <li><strong>Usage Data:</strong> This is collected automatically and may include your Device's IP address, browser type, pages visited, the time and date of your visit, and other diagnostic data. This helps us understand how our Service is used and how to improve it.</li>
                        </ul>

                        <h3 className="text-xl font-semibold text-foreground">How We Use Your Data</h3>
                        <p>The Company uses the collected data for several purposes:</p>
                         <ul className="list-disc pl-6 space-y-2">
                            <li>To provide, maintain, and improve our Service.</li>
                            <li>To monitor the usage of our Service and analyze trends.</li>
                            <li>To detect, prevent, and address technical issues.</li>
                            <li>To provide you with news and general information about our services, should we introduce such features in the future.</li>
                        </ul>
                    </div>
                    
                    <div className="space-y-4">
                        <h2 className="text-2xl font-semibold text-foreground">3. Changes to this Privacy Policy</h2>
                        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the "Last updated" date at the top. We encourage you to review this Privacy Policy periodically for any changes.</p>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-2xl font-semibold text-foreground">4. Contact Us</h2>
                        <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:support@tunedetective.com" className="underline hover:text-primary">support@tunedetective.com</a>.</p>
                    </div>
                </CardContent>
            </Card>
        </main>
    );
}
