import { Music } from "lucide-react";
import Link from "next/link";

export default function PrivacyPolicyPage() {
    return (
        <div className="min-h-screen w-full bg-gray-50 font-body">
            <header className="bg-primary text-primary-foreground py-4">
                <div className="container mx-auto px-4 flex justify-between items-center">
                    <Link href="/" className="text-4xl font-black tracking-tighter flex items-center justify-center">
                        <span>TRACK</span>
                        <Music className="w-8 h-8 mx-1 text-white fill-white" />
                        <span>BPM</span>
                    </Link>
                </div>
            </header>

            <main className="container mx-auto px-4 py-8">
                <div className="max-w-3xl mx-auto prose prose-lg">
                    <h1>Privacy Policy</h1>
                    <p>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

                    <p>This Privacy Policy outlines our procedures and policies on the collection, usage, and disclosure of your information when you utilize our Service. It also informs you about your privacy rights and how the law protects you.</p>

                    <h2>Interpretation and Definitions</h2>
                    <h3>Interpretation</h3>
                    <p>Words with initial capital letters have defined meanings under the following conditions. These definitions will apply regardless of whether they appear in singular or plural form.</p>

                    <h3>Definitions</h3>
                    <p>For this Privacy Policy:</p>
                    <ul>
                        <li><strong>Account</strong> means a unique account created for you to access our Service or parts of it.</li>
                        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to TRACKBPM.</li>
                        <li><strong>Cookies</strong> are small files placed on your computer, mobile device, or any other device by a website, containing details of your browsing history on that website among its many uses.</li>
                        <li><strong>Country</strong> refers to: United States</li>
                        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Service</strong> refers to the Website.</li>
                        <li><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, perform services related to the Service, or assist the Company in analyzing how the Service is used.</li>
                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                        <li><strong>Website</strong> refers to TRACKBPM, accessible from the current domain.</li>
                        <li><strong>You</strong> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>

                    <h2>Collecting and Using Your Personal Data</h2>
                    <h3>Types of Data Collected</h3>
                    <h4>Personal Data</h4>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to, Usage Data.</p>
                    <h4>Usage Data</h4>
                    <p>Usage Data is collected automatically when using the Service. It may include information such as your Device's IP address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, time spent on those pages, and other diagnostic data.</p>

                    <h2>Use of Your Personal Data</h2>
                    <p>The Company may use Personal Data for the following purposes:</p>
                    <ul>
                        <li>To provide and maintain our Service.</li>
                        <li>To manage Your Account.</li>
                        <li>For the performance of a contract.</li>
                        <li>To contact You by email or other electronic communication.</li>
                        <li>To provide You with news and general information about our services.</li>
                    </ul>

                    <h2>Changes to this Privacy Policy</h2>
                    <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                </div>
            </main>
        </div>
    );
}
